import assert from 'node:assert/strict';
import * as invocation from '../server/harness/tool_invocation.js';
assert.equal(typeof invocation.ToolInvocationService, 'function', 'canonical invocation service is required');
let body=0, approvals=0;
const records=[], controller=new AbortController();
const run={runId:'r',sessionId:'s',agentId:'a',scope:{scopeId:'standalone:s'},signal:controller.signal,capabilities:['write']};
run.runTools={validateCall(call){if(call.name!=='write'||typeof call.arguments.value!=='string')throw new Error('Invalid schema');return {tool:{execute:async args=>{body++;return {value:args.value};}}};}};
const service=new invocation.ToolInvocationService({resolveRun:id=>id==='r'?run:null,authorize:async()=>{approvals++;return {action:'ALLOW'};},record:(_run,event)=>records.push(event)});
const call={id:'c',name:'write',arguments:{value:'original'}};
const [a,b]=await Promise.all([service.invoke({call,context:{runId:'r'}}),service.invoke({call,context:{runId:'r'}})]);
assert.equal(a,b);assert.equal(body,1);assert.equal(approvals,1);assert.equal(records.filter(e=>e.type==='tool/result').length,1);
assert.equal(records[0].type,'tool/call');assert.equal(a.output.value,'original');assert(Object.isFrozen(a));
await assert.rejects(service.invoke({call:{...call,arguments:{value:'different'}},context:{runId:'r'}}),/collision/i);
const remove=service.registerGuard('deny',()=>({action:'DENY',reason:'guard denied'}));
assert.equal((await service.invoke({call:{...call,id:'guard'},context:{runId:'r'}})).status,'denied');assert.equal(body,1);remove();
assert.equal((await service.invoke({call:{...call,id:'bad',arguments:{}},context:{runId:'r'}})).status,'denied');assert.equal(body,1);
assert.equal((await service.invoke({call:{...call,id:'foreign'},context:{runId:'r',sessionId:'other'}})).status,'denied');
controller.abort();assert.equal((await service.invoke({call:{...call,id:'cancel'},context:{runId:'r'}})).status,'cancelled');assert.equal(body,1);
const denied=new invocation.ToolInvocationService({resolveRun:()=>({...run,signal:new AbortController().signal}),authorize:async()=>({action:'DENY',reason:'Approval provider unavailable'}),record:()=>{}});
assert.equal((await denied.invoke({call,context:{runId:'r'}})).status,'denied');assert.equal(body,1);
console.log('Canonical invocation policy, identity, guards and cancellation passed');
const waiting=Promise.withResolvers(),entered=Promise.withResolvers(),lateAbort=new AbortController();let lateBodies=0;
const lateRun={...run,signal:lateAbort.signal,runTools:{validateCall:()=>({tool:{execute:()=>{lateBodies++;return {changed:true};}}})}};
const late=new invocation.ToolInvocationService({resolveRun:()=>lateRun,authorize:async()=>({action:'ALLOW'}),pipeline:async(_call,_ctx,execute)=>{entered.resolve();await waiting.promise;return execute();}});
const lateResult=late.invoke({call:{...call,id:'late'},context:{runId:'r'}});await entered.promise;lateAbort.abort();waiting.resolve();
assert.equal((await lateResult).status,'cancelled');assert.equal(lateBodies,0,'abort while middleware waits must prevent mutation');
