const {app,BrowserWindow}=require('electron');const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'harness-surfaces-'));app.setPath('userData',path.join(temp,'electron'));
app.whenReady().then(async()=>{const {createDaemon}=await import('../server/index.js');const daemon=createDaemon({dbPath:':memory:',port:0,dataDir:temp});daemon.db.createSession('surface',daemon.db.getAgents()[0].id,'Surface review');const artifact=daemon.harness.artifacts.save({sessionId:'surface',scopeId:'standalone',title:'Verified document.html',mime:'text/html',content:'<h1>Verified document</h1><script>parent.document.body.dataset.escaped="yes"</script>'});const {port}=await daemon.start();const w=new BrowserWindow({width:1280,height:800,show:true});const output=path.resolve('.superpowers/sdd/2026-10-09-harness-full/ui');fs.mkdirSync(output,{recursive:true});
try{
 await w.loadURL(`http://127.0.0.1:${port}/#session/surface`);await new Promise(r=>setTimeout(r,800));await w.webContents.executeJavaScript(`window.dispatchEvent(new CustomEvent('ohmyt-artifact-open',{detail:${JSON.stringify(artifact)}}))`);await new Promise(r=>setTimeout(r,350));assert.match(await w.webContents.executeJavaScript('document.body.innerText'),/Verified document/);assert.equal(await w.webContents.executeJavaScript('document.body.dataset.escaped'),undefined);assert.equal(await w.webContents.executeJavaScript(`document.querySelector('.harness-artifact-pane iframe').getAttribute('sandbox')`),'');fs.writeFileSync(path.join(output,'artifact.png'),(await w.webContents.capturePage()).toPNG());
 console.log('Opening connections');await w.webContents.executeJavaScript("location.hash='#settings/connectors';true");await new Promise(r=>setTimeout(r,650));assert.match(await w.webContents.executeJavaScript('document.body.innerText'),/Add connection|Thêm kết nối/);fs.writeFileSync(path.join(output,'connectors.png'),(await w.webContents.capturePage()).toPNG());
 await w.webContents.executeJavaScript("location.hash='#settings/extensions';true");await new Promise(r=>setTimeout(r,650));assert.match(await w.webContents.executeJavaScript('document.body.innerText'),/Cấu hình agent|Agent presets/);
 for(const [width,height] of [[1280,800],[1440,900],[1920,1080],[768,700]]){w.setSize(width,height);await new Promise(r=>setTimeout(r,180));assert.equal(await w.webContents.executeJavaScript('document.documentElement.scrollWidth>window.innerWidth'),false,`overflow at ${width}`);fs.writeFileSync(path.join(output,`extensions-${width}.png`),(await w.webContents.capturePage()).toPNG());}
 for(const locale of ['vi','en'])for(const theme of ['light','dark']){await w.webContents.executeJavaScript(`localStorage.setItem('ohmyt_appearance',JSON.stringify({themeMode:'${theme}',locale:'${locale}',responseAnimation:'off',transition:'none'}));true`);await w.loadURL(`http://127.0.0.1:${port}/?variant=${locale}-${theme}#settings/extensions`);await new Promise(r=>setTimeout(r,600));assert.equal(await w.webContents.executeJavaScript('document.documentElement.lang'),locale);assert.equal(await w.webContents.executeJavaScript('document.documentElement.dataset.theme'),theme);for(const [width,height] of [[1280,800],[1440,900],[1920,1080],[768,700]]){w.setSize(width,height);await new Promise(r=>setTimeout(r,130));assert.equal(await w.webContents.executeJavaScript('document.documentElement.scrollWidth>innerWidth'),false);fs.writeFileSync(path.join(output,`extensions-${locale}-${theme}-${width}.png`),(await w.webContents.capturePage()).toPNG());}}
 const probe=await daemon.harness.ptc.probe();fs.writeFileSync(path.join(output,'electron-ptc-probe.json'),JSON.stringify(probe));assert(probe.available,'Electron PTC must actually pass process isolation probe');console.log('Actual artifact sandbox, connector/preset surfaces, viewport layouts and Electron PTC passed');
}finally{w.close();await daemon.stop();fs.rmSync(temp,{recursive:true,force:true});}app.quit();}).catch(e=>{console.error(e);app.exit(1);});
