const {app,BrowserWindow}=require('electron');
const assert=require('node:assert/strict');
const {IntegratedBrowser}=require('../electron/browser.cjs');
app.whenReady().then(async()=>{
 const host=new BrowserWindow({width:1100,height:750,show:true});
 await host.loadURL('about:blank');
 const browser=new IntegratedBrowser();
 const requested=[];
 browser.add=url=>{requested.push(url);return browser.addTab('about:blank');};
 const bounds={x:500,y:30,width:580,height:680};
 browser.attach(host,null,false);
 browser.setChat('chat-a');
 browser.attach(host,bounds,true);
 const first=browser.active;
 assert.equal(browser.tabs.get(first).chatId,'chat-a');
 browser.expanded=true;
 browser.attach(host,null,false);
 browser.setChat('chat-b');
 assert.equal(browser.expanded,false);
 assert.equal(browser.active,null);
 assert.equal(browser.tabs.size,1,'switching alone must retain A without creating a hidden B tab');
 browser.attach(host,bounds,true);
 const second=browser.active;
 assert.notEqual(second,first);
 assert.equal(browser.tabs.get(second).chatId,'chat-b');
 assert.deepEqual(requested,['https://www.google.com','https://www.google.com'],'each newly opened chat must receive a default Google tab');
 browser.attach(host,null,false);
 browser.setChat('chat-a');
 browser.attach(host,bounds,true);
 assert.equal(browser.active,first,'returning must restore the original chat tab');
 assert.equal(browser.tabs.size,2,'returning must not create duplicate tabs');
 assert.equal(browser.tabs.get(second).getVisible(),false);
 browser.setChat('chat-c');
 browser.attach(host,null,false);
 assert.equal(browser.tabs.size,2,'closed pane in an unused chat must not create tabs');
 console.log('PASS chat browser panes: new chat opens Google, previous tabs retained, no duplicate or hidden tabs');
 host.destroy();app.quit();
}).catch(e=>{console.error(e);app.exit(1);});
