import assert from 'node:assert/strict';
import {validateImages,messageContent} from '../server/image_attachments.js';
import {toGeminiContents} from '../server/providers/adapters/google.js';
import {toAnthropicMessages} from '../server/providers/adapters/anthropic.js';
import {AppDatabase} from '../server/db.js';
import {ToolRegistry} from '../server/tools.js';
import {PermissionEngine} from '../server/permissions.js';
import {AgentLoop} from '../server/agent_loop.js';
import {createApiServer} from '../server/api.js';
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
const images=[{name:'screen.png',dataUrl:'data:image/png;base64,'+png}];
assert.deepEqual(validateImages(images),images);
assert.throws(()=>validateImages([...images,...images,...images,...images,...images]));
assert.throws(()=>validateImages([{...images[0],dataUrl:'data:image/svg+xml;base64,AAAA'}]));
assert.throws(()=>validateImages([{...images[0],dataUrl:'data:image/png;base64,YWJjZA=='}]));
assert.throws(()=>validateImages([{...images[0],dataUrl:'data:image/png;base64,'+'A'.repeat(6000000)}]));
const message={role:'user',content:messageContent({content:'Xem ảnh',metadata:JSON.stringify({images})})};
assert.deepEqual(toGeminiContents([message])[0].parts,[{inlineData:{mimeType:'image/png',data:png}},{text:'Xem ảnh'}]);
assert.deepEqual(toAnthropicMessages([message]).messages[0].content,[{type:'image',source:{type:'base64',media_type:'image/png',data:png}},{type:'text',text:'Xem ảnh'}]);
assert.equal(messageContent({content:'text'}),'text');
const db=new AppDatabase(':memory:');
db.upsertAgent({avatar:'T',id:'images',name:'Test',system_prompt:'Test',model_provider:'custom',model_name:'test',temperature:.7});
db.createSession('images','images','Image test');
db.updateSession('images','Image test');
const turns=[];
const loop=new AgentLoop({db,tools:new ToolRegistry(db),permissions:new PermissionEngine(db),skills:{},llm:{streamChat:async options=>{turns.push(options.messages);options.onChunk('Ảnh đã nhận.');return {completed:true};}}});
await loop.run({runId:'image-only',sessionId:'images',prompt:'',images});
assert.deepEqual(JSON.parse(db.getMessages('images')[0].metadata).images,images);
assert.equal(turns[0].find(m=>m.role==='user').content[0].image_url.url,images[0].dataUrl);
await loop.run({runId:'image-followup',sessionId:'images',prompt:'Ảnh trước có gì?'});
assert.equal(turns[1].find(m=>Array.isArray(m.content)).content[0].image_url.url,images[0].dataUrl);
const api=createApiServer({db,tools:new ToolRegistry(db),permissions:new PermissionEngine(db),skills:{},llm:{},agentLoop:loop});
const address=await api.listen(0);
try {
  const base=`http://127.0.0.1:${address.port}`;
  const invalid=await fetch(base+'/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:'images',prompt:'',images:[{name:'bad',dataUrl:'file:///etc/passwd'}]})});
  assert.equal(invalid.status,400);
  const response=await fetch(base+'/api/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:'images',prompt:'',images})});
  assert.equal(response.status,202);
  await new Promise(resolve=>setTimeout(resolve,100));
  const history=await (await fetch(base+'/api/sessions/images/messages')).json();
  assert.equal(history.filter(m=>m.sender==='user'&&JSON.parse(m.metadata||'{}').images?.length).length,2);
} finally {await api.close();db.close();}
console.log('PASS images: validation, provider conversion, API image-only, persistence and follow-up context');
