import assert from 'node:assert/strict';
import {AppDatabase} from '../server/db.js';
import {SessionLog} from '../server/harness/log.js';
import {projectModelHistory} from '../server/harness/projections.js';
const db=new AppDatabase(':memory:');const s=db.getSessions()[0];
const sessionId=s?.id || 'log-s';if(!s)db.createSession(sessionId,db.getAgents()[0].id,'Log');
const log=new SessionLog(db);const event={eventId:'start',type:'turn/start',payload:{turnId:'r'}};
assert.equal(log.append(sessionId,0,[event])[0].seq,1);
assert.equal(log.append(sessionId,0,[event])[0].seq,1);
assert.throws(()=>log.append(sessionId,0,[{...event,eventId:'new'}]),/sequence/i);
assert.throws(()=>log.append(sessionId,1,[{eventId:'valid',type:'step/start',payload:{}},{eventId:'bad',type:'invalid',payload:{}}]));
assert.equal(log.read(sessionId).length,1,'batch must be atomic');
log.append(sessionId,1,[{eventId:'assistant',type:'message/assistant',payload:{turnId:'r',message:{role:'assistant',content:'',tool_calls:[{id:'c',function:{name:'write',arguments:'{}'}}]}}}]);
const projected=projectModelHistory(log.read(sessionId));assert.equal(projected[1].role,'tool');assert.equal(projected[1].tool_call_id,'c');assert.match(projected[1].content,/unknown/i);
db.db.prepare('DELETE FROM harness_events WHERE session_id=?').run(sessionId);
assert.equal(log.sequence(sessionId),2,'deletion must never rewind durable cursor');
assert.equal(log.append(sessionId,2,[{eventId:'after-delete',type:'turn/start',payload:{}}])[0].seq,3);
db.db.prepare('DELETE FROM sessions WHERE id=?').run(sessionId);assert.equal(log.read(sessionId).length,0);
db.close();console.log('Semantic log atomicity, dedupe, projection and cascade passed');
