import assert from 'node:assert/strict';
import {AppDatabase} from '../server/db.js';
import {SessionStore} from '../server/harness/sessions.js';
import {projectModelHistory} from '../server/harness/projections.js';
const db=new AppDatabase(':memory:');db.createSession('s',db.getAgents()[0].id,'Fixture');
db.addMessage('u1','s','user','same');db.addMessage('a1','s','agent','answer');db.addMessage('u2','s','user','same');
const store=new SessionStore(db);
assert.equal(typeof store.migrateHistory,'function','history migration must offer a dry run');
const before=store.log.sequence('s'),preview=store.migrateHistory('s',{dryRun:true});assert.equal(preview.equal,true);assert.equal(store.log.sequence('s'),before);
const migrated=store.migrateHistory('s');assert.equal(migrated.equal,true);const seq=store.log.sequence('s');assert.deepEqual(store.modelHistory('s').map(m=>m.content),['same','answer','same']);
assert.equal(store.migrateHistory('s').equal,true);assert.equal(store.log.sequence('s'),seq);
const ids=store.log.readAll('s').filter(e=>e.payload.historySource==='migration').map(e=>e.payload.messageId);assert.equal(new Set(ids).size,3);
db.deleteMessage('u1');assert.deepEqual(store.modelHistory('s').map(m=>m.content),['answer','same'],'deleted identity must not erase the other identical message');
const call={role:'assistant',content:'',tool_calls:[{id:'c',function:{name:'write',arguments:'{}'}}]};
const events=[{type:'message/assistant',payload:{turnId:'r',message:call}},{type:'tool/result',payload:{turnId:'r',message:{role:'tool',name:'write',tool_call_id:'c',content:'{"success":true}'}}},{type:'tool/result',payload:{turnId:'r',callId:'c',modelContent:'{"error":"denied"}',status:'denied'}}];
assert.match(projectModelHistory(events)[1].content,/denied/,'committed receipt must override a contradictory model result');
db.db.prepare("UPDATE harness_migration_state SET through_seq=99999 WHERE session_id='s'").run();
assert.throws(()=>store.migrateHistory('s'),/coverage|marker/i,'corrupt completed marker must not report success');
db.close();console.log('History dry-run, identity, idempotent migration and receipt authority passed');
