import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createDaemon} from '../server/index.js';
import {createRunScope} from '../server/project_scope.js';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ohmyt-local-'));
const d=createDaemon({dbPath:':memory:',workspaceRoot:dir,hostEnabled:true,port:0,authToken:'test-token'});
try {
 assert(d.tools.get('shell_host'));assert(d.tools.get('runtime_info'));
 const runtimeCall=d.tools.validateCall({name:'runtime_info',arguments:{reason:'Check the browser execution environment'}});
 assert.deepEqual(await runtimeCall.tool.execute(runtimeCall.arguments),d.tools.describeRuntime());
 assert.doesNotThrow(()=>d.tools.validateCall({name:'runtime_info',arguments:{}}));
 assert.throws(()=>d.tools.validateCall({name:'runtime_info',arguments:{reason:42}}),/must be string/);
 assert.throws(()=>d.tools.validateCall({name:'runtime_info',arguments:{command:'ignored'}}),/Unknown argument/);
 const standaloneRuntime=d.tools.forStandalone({scopeId:'standalone:runtime-reason'});
 const standaloneCall=standaloneRuntime.validateCall({name:'runtime_info',arguments:{reason:'Check standalone capabilities'}});
 assert.deepEqual(await standaloneCall.tool.execute(standaloneCall.arguments),standaloneRuntime.describeRuntime());
 assert.equal(d.permissions.evaluate('shell_host','echo test').action,'ASK');
 const cmd=process.platform==='win32'?"Write-Output 'host-runtime-ok'":"printf host-runtime-ok";
 const output=await d.tools.get('shell_host').execute({command:cmd,cwd:dir},{runId:'host-test'});
 assert(output.success);assert(output.stdout.includes('host-runtime-ok'));
 assert.equal(d.tools.activeChildProcesses.size,0);
 const projectRoot=path.join(dir,'project');fs.mkdirSync(projectRoot);
 d.db.addProject('host-project','Host project',projectRoot);
 d.db.createSession('host-session','default-assistant','Host test','host-project');
 const scope=createRunScope(d.db,d.db.getSession('host-session'),'project-host-test');
 const projectTools=d.tools.forWorkspace(projectRoot,scope);
 assert.ok(projectTools.get('shell_host'));
 assert.equal(d.permissions.evaluate('shell_host','host-command',scope).action,'ASK');
 const approval=d.permissions.requestApproval({runId:'project-host-test',toolName:'shell_host',target:'host-command',scope});
 d.permissions.resolveApproval(approval.requestId,'ALLOW_ALWAYS');assert.equal((await approval.promise).allowed,true);
 assert.equal(d.permissions.evaluate('shell_host','host-command',scope).action,'ALLOW');
 assert.equal(d.permissions.evaluate('shell_host','different-command',scope).action,'ASK');
 d.db.setPolicy('shell_host:blocked-command','DENY');
 assert.equal(d.permissions.evaluate('shell_host','blocked-command',scope).action,'DENY');
 const outside=path.join(dir,'outside-project.txt');
 const writeCommand=`node -e "require('fs').writeFileSync('../outside-project.txt','host-file-ok');process.stdout.write(require('fs').readFileSync('../outside-project.txt','utf8'))"`;
 const hostFile=await projectTools.get('shell_host').execute({command:writeCommand},{runId:'project-host-test'});
 assert.equal(hostFile.success,true);assert.equal(hostFile.stdout,'host-file-ok');
 assert.equal(fs.readFileSync(outside,'utf8'),'host-file-ok');
 assert.equal(d.tools.forStandalone({scopeId:'standalone:host-test'}).describeRuntime().workspaceRoot,os.homedir());

 const address=await d.start();const base=`http://127.0.0.1:${address.port}/api/sessions`;
 assert.equal((await fetch(base)).status,401);
 assert.equal((await fetch(base,{headers:{Authorization:'Bearer wrong'}})).status,401);
 assert.equal((await fetch(base,{headers:{Authorization:'Bearer test-token'}})).status,200);
 const other=createDaemon({dbPath:':memory:',workspaceRoot:dir});
 assert.equal(other.tools.get('shell_host'),undefined);other.db.close();
 console.log('✓ Native execution, permission gate, cleanup, authenticated loopback API and opt-in host mode passed');
}finally{await d.stop();fs.rmSync(dir,{recursive:true,force:true});}
