import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { EventEmitter } from 'node:events';
import { BrowserBridge } from '../server/browser_bridge.js';
import { chromeExtensionArchive } from '../server/chrome_extension_package.js';
import { AppDatabase } from '../server/db.js';
import { ToolRegistry } from '../server/tools.js';
import { AgentLoop } from '../server/agent_loop.js';
import { PermissionEngine } from '../server/permissions.js';
import { createApiServer } from '../server/api.js';

const bridge = new BrowserBridge();
const db = new AppDatabase(':memory:');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ohmyt-chrome-test-'));
const tools = new ToolRegistry(db, root);
bridge.registerTools(tools);
assert.doesNotThrow(()=>tools.validateCall({name:'browser_tabs',arguments:{reason:'Inspect shared tabs'}}));
assert.throws(()=>tools.validateCall({name:'browser_tabs',arguments:{reason:42}}),/must be string/);
assert.throws(()=>tools.validateCall({name:'browser_tabs',arguments:{arbitrary:true}}),/Unknown argument/);
const api = createApiServer({db, tools, agentLoop:new EventEmitter(), browserBridge:bridge, port:0});
const site = [{id:7,title:'Test page',url:'https://example.com/form'},{id:8,title:'Other page',url:'https://other.example/'}];
let base, token;
const device = async (route, body, auth = token, origin) => {
  return fetch(base + route, {method:body === undefined ? 'GET' : 'POST',headers:{Authorization:`Bearer ${auth}`, 'Content-Type':'application/json', ...(origin ? {Origin:origin} : {})},...(body === undefined ? {} : {body:JSON.stringify(body)})});
};
const respond = async (promise, result, error) => {
  const queued = await (await device('/poll')).json();
  assert.equal(queued.length, 1);
  await device('/result', {id:queued[0].id, result, error});
  return promise;
};
try {
  const native=new BrowserBridge();let nativeTabs=[{id:101,title:'Native',url:'https://example.com/'}];
  native.nativeCommand=async(action,args)=>action==='tabs'?nativeTabs:{action,tabId:args.tabId};
  await native.prepareSession('native-chat');
  assert.equal((await native.execute('native-chat','read',{tabId:101})).action,'read');
  nativeTabs.push({id:102,title:'New tab',url:'https://github.com/'});
  assert.equal((await native.execute('other-chat','tabs')).length,2);
  assert.equal((await native.execute('native-chat','navigate',{tabId:102,url:'https://example.org/'})).action,'navigate');
  nativeTabs=[];await assert.rejects(native.execute('native-chat','read',{tabId:101}),/chưa được chia sẻ/);
  await native.close();
  await assert.rejects(bridge.command('tabs'), /chưa kết nối/);
  const pairing = await bridge.pairing();
  const connection = new URL(pairing.connection); base = connection.origin;
  assert.equal((await device('/connect', {}, 'bad')).status, 401);
  assert.equal((await device('/connect', {}, connection.hash.slice(1), 'https://malicious.example')).status, 403);
  token = (await (await device('/connect', {}, connection.hash.slice(1), 'chrome-extension://' + 'a'.repeat(32))).json()).token;
  assert.ok(token);
  assert.equal((await device('/connect', {}, connection.hash.slice(1))).status, 401);
  assert.equal((await device('/poll', undefined, 'bad')).status, 401);
  assert.equal(bridge.status('chat').connected, true);
  const share = bridge.share('chat', [7]);
  await respond(share, site);
  assert.deepEqual(await bridge.execute('chat','tabs'), [{...site[0],origin:'https://example.com'}]);
  await assert.rejects(bridge.execute('other-chat','read',{tabId:7}), /Chưa chia sẻ/);
  await assert.rejects(bridge.execute('chat','read',{tabId:8}), /chưa được chia sẻ/);
  await assert.rejects(bridge.execute('chat','navigate',{tabId:7,url:'https://other.example/'}), /tên miền khác/);
  const read = bridge.execute('chat','read',{tabId:7});
  const queued = await (await device('/poll')).json();
  assert.equal(queued[0].args.expectedOrigin, 'https://example.com');
  await device('/result', {id:queued[0].id,result:{text:'test page'}});
  assert.deepEqual(await read, {text:'test page'});
  const aborted = new AbortController();
  const abortPromise = bridge.execute('chat','read',{tabId:7},aborted.signal);
  const abortCheck = assert.rejects(abortPromise, /Đã dừng/); aborted.abort(); await abortCheck;
  assert.equal(bridge.queue.length,0);
  const revoked = bridge.execute('chat','click',{tabId:7,elementId:'old'});
  const revokeCheck = assert.rejects(revoked, /thu hồi/); bridge.revoke('chat'); await revokeCheck;
  assert.equal(bridge.queue.length,0);
  await assert.rejects(bridge.execute('chat','read',{tabId:7}), /Chưa chia sẻ/);
  await respond(bridge.share('chat',[7]),site);
  const registryScope = {projectId:'proj',scopeId:'project:proj',canonicalRoot:root};
  assert.ok(tools.forWorkspace(root,registryScope).get('browser_read'));
  const permissions = new PermissionEngine(db);
  assert.equal(permissions.evaluate('browser_click','7',registryScope).action,'ASK');
  assert.equal(permissions.evaluate('unknown_browser_tool','',registryScope).action,'DENY');

  const {port} = await api.listen(0);
  const app = `http://127.0.0.1:${port}/api`;
  db.createSession('chat','default-assistant','Browser test');
  const request = (route,body) => fetch(app + route,{method:body ? 'POST':'GET',headers:{'Content-Type':'application/json'},...(body ? {body:JSON.stringify(body)} : {})});
  assert.equal((await request('/chrome/share',{sessionId:'missing',tabIds:[7]})).status,404);
  assert.equal((await request('/chrome/share',{sessionId:'chat',tabIds:['bad']})).status,400);
  assert.equal((await request('/chrome/status?sessionId=chat')).status,200);
  const archive = await request('/chrome/extension');
  assert.equal(archive.headers.get('content-type'),'application/zip');
  assert.equal(Buffer.from(await archive.arrayBuffer()).readUInt32LE(0),0x04034b50);

  // Real agent loop: an explicitly shared tab works despite the default LOCAL_ONLY policy.
  const loop = new AgentLoop({db,tools,permissions:{evaluate:()=>({action:'ALLOW'})},skills:{},llm:{streamChat:async ({messages,onToolCall,onChunk}) => {
    if (!messages.some(message => message.content.includes('[TOOL_RESULT for'))) onToolCall({id:'chrome-tabs',name:'browser_tabs',arguments:{reason:'Check the tabs shared by the user'}});
    else if (!messages.some(message => message.content.includes('[TOOL_RESULT for browser_read'))) onToolCall({id:'chrome-read',name:'browser_read',arguments:{tabId:7,reason:'Inspect the selected page'}});
    else onChunk('The selected page contains test content.');
    return {completed:true};
  }}});
  const run = loop.run({runId:'chrome-run',sessionId:'chat',prompt:'Read the shared Chrome tab'});
  const poll = await (await device('/poll')).json();
  assert.equal(poll[0].action,'read');
  await device('/result',{id:poll[0].id,result:{text:'test content'}});
  await run;
  assert.equal(db.db.prepare('SELECT status FROM runs WHERE id = ?').get('chrome-run').status,'completed');
  await request('/chrome/share',{sessionId:'chat',tabIds:[]});
  assert.deepEqual(bridge.status('chat').tabs,[]);
  const pending = bridge.command('tabs'); const pendingCheck = assert.rejects(pending,/ngắt kết nối/);
  await device('/disconnect',{}); await pendingCheck;
  assert.equal(bridge.status('chat').connected,false);
  assert.equal((await device('/poll')).status,401);
  const fresh = await bridge.pairing(); const freshUrl = new URL(fresh.connection);
  token = (await (await device('/connect',{},freshUrl.hash.slice(1))).json()).token;
  assert.deepEqual(bridge.status('chat').tabs,[]);
  bridge.lastSeen = Date.now() - 40000;
  assert.equal(bridge.status('chat').connected,false);
  fs.writeFileSync(path.join(root,'extension.zip'),chromeExtensionArchive());
  console.log('✓ Chrome bridge: pairing/auth, origin protection, per-chat grants, revocation/abort, reconnection, tools, agent loop and API');
} finally { await api.close(); await bridge.close(); db.close(); fs.rmSync(root,{recursive:true,force:true}); }
