const {app,BrowserWindow} = require('electron');
const assert = require('node:assert/strict');
const {IntegratedBrowser} = require('../electron/browser.cjs');
const {htmlPreviewUrl} = require('../electron/html-preview.cjs');
assert.throws(()=>htmlPreviewUrl(''));
assert.throws(()=>htmlPreviewUrl('x'.repeat(2100000)));
app.whenReady().then(async()=>{
  const browser = new IntegratedBrowser();
  const host = new BrowserWindow({show:false});
  browser.attach(host,{x:0,y:0,width:800,height:600});
  const html = '<!doctype html><title>Canvas demo</title><canvas id="game"></canvas><script>const ctx=document.getElementById("game").getContext("2d");ctx.fillStyle="purple";ctx.fillRect(0,0,100,100);</script>';
  const id = browser.addPreview(html);
  const wc = browser.tabs.get(id).webContents;
  await new Promise((resolve,reject)=>{wc.once('did-finish-load',resolve);wc.once('did-fail-load',(_e,_c,d)=>reject(new Error(d)));});
  assert.equal(browser.active,id);
  assert.equal(browser.tabs.get(id).getVisible(),true);
  assert.equal(wc.getTitle(),'Canvas demo');
  assert.deepEqual(await wc.executeJavaScript('Array.from(document.getElementById("game").getContext("2d").getImageData(10,10,1,1).data)'),[128,0,128,255]);
  assert.equal(await wc.executeJavaScript('typeof require'),'undefined');
  assert.equal(browser.state().tabs.find(t=>t.id===id).url,'Preview HTML');
  assert.ok(browser.url('data:text/html,test').startsWith('https://www.google.com/search?'));
  wc.reload();
  await new Promise(resolve=>wc.once('did-finish-load',resolve));
  assert.equal(wc.getTitle(),'Canvas demo');
  if(browser.controls.webContents.isLoading()) await new Promise(resolve=>browser.controls.webContents.once('did-finish-load',resolve));
  const expansions=[];
  const originalSend=host.webContents.send.bind(host.webContents);
  host.webContents.send=(channel,...args)=>{if(channel==='browser-pane-expand')expansions.push(args[0]);else originalSend(channel,...args);};
  await browser.controls.webContents.executeJavaScript("browserUI.command('expand')");
  assert.equal(browser.state().expanded,true);
  browser.attach(host,{x:4,y:4,width:1000,height:700});
  assert.equal(browser.tabs.get(id).getBounds().width,1000);
  assert.equal(browser.active,id);
  await browser.controls.webContents.executeJavaScript("browserUI.command('expand')");
  assert.equal(browser.state().expanded,false);
  assert.deepEqual(expansions,[true,false]);
  browser.attach(host,{x:400,y:40,width:400,height:600});
  assert.equal(browser.tabs.get(id).getBounds().width,400);
  browser.remove(id);
  console.log('PASS embedded HTML canvas: render, tab, reload, no Node access');
  host.close();app.quit();
}).catch(error=>{console.error(error);app.exit(1);});
