import assert from 'node:assert/strict';
import {createDaemon} from '../server/index.js';
const daemon=createDaemon({dbPath:':memory:',port:0});await daemon.harness.ready;
daemon.db.createSession('preset-chat',daemon.db.getAgents()[0].id,'Preset chat');const profiles=daemon.harness.profiles;
profiles.save({id:'global-profile',version:1,name:'Global',budgets:{maxSteps:7}},0);profiles.select('global-profile');assert.equal(profiles.selected('preset-chat').budgets.maxSteps,7);
profiles.save({id:'chat-profile',version:1,name:'Chat',budgets:{maxSteps:3}},0);profiles.select('chat-profile',{sessionId:'preset-chat'});assert.equal(profiles.selected('preset-chat').budgets.maxSteps,3);assert.equal(profiles.selected().budgets.maxSteps,7);
assert.throws(()=>profiles.save({id:'bad-budget',version:1,budgets:{contextTokens:10}},0),/Reserve/);assert.throws(()=>profiles.save({id:'bad-scope',version:1,scope:'project:unowned'},0),/scope/);
profiles.save({id:'small',version:1,budgets:{contextTokens:100,reserveTokens:10}},0);
profiles.save({id:'reserve',version:1,budgets:{reserveTokens:200}},0);
profiles.select('small');
assert.throws(()=>profiles.select('reserve',{sessionId:'preset-chat'}),/Reserve/);
assert.equal(profiles.selectedId('preset-chat'),'chat-profile');
profiles.select('global-profile');profiles.select('reserve',{sessionId:'preset-chat'});
assert.throws(()=>profiles.select('small'),/Reserve/);
assert.equal(profiles.selectedId(),'global-profile');
assert.throws(()=>profiles.save({id:'global-profile',version:1,budgets:{contextTokens:100,reserveTokens:10}},1),/Reserve/);
assert.equal(profiles.get('global-profile').revision,1);
assert.equal(profiles.selected('preset-chat').budgets.reserveTokens,200);
daemon.db.db.prepare('INSERT INTO projects(id,name,path,created_at) VALUES(?,?,?,?)').run('preset-project','Preset project','/tmp/preset-project',Date.now());
daemon.db.createSession('project-chat',daemon.db.getAgents()[0].id,'Project chat','preset-project');
profiles.select('reserve',{sessionId:'project-chat'});
assert.throws(()=>profiles.select('small',{projectId:'preset-project'}),/Reserve/);
assert.equal(daemon.db.db.prepare('SELECT COUNT(*) AS n FROM harness_project_profiles').get().n,0);
assert.equal(profiles.selected('project-chat').budgets.reserveTokens,200);
daemon.db.deleteSession('project-chat');
daemon.db.deleteSession('preset-chat');assert.equal(daemon.db.db.prepare('SELECT COUNT(*) AS n FROM harness_session_profiles').get().n,0);
await daemon.stop();console.log('Persistent global/session profile layering, validation and deletion passed');
