import assert from 'node:assert/strict';
import { AgentLoop } from '../server/agent_loop.js';
import { AppDatabase } from '../server/db.js';
import { isDefaultTitle, isGreeting, fallbackTitle, generateTitle } from '../server/session_titles.js';
const db = new AppDatabase(':memory:');
db.upsertAgent({id:'title-agent',name:'Title',avatar:'T',system_prompt:'Test',model_provider:'ollama',model_name:'test',temperature:.7});
const s = db.createSession('title-session','title-agent','Phiên làm việc 17');
assert(isDefaultTitle(s.title));
assert(!isDefaultTitle('Tên do tui đặt'));
const history = [{sender:'user',content:'chào bạn nha'}, {sender:'user',content:'Thiết kế icon trạng thái Thinking giúp tui'}];
assert.equal(fallbackTitle(history), 'Thiết kế icon trạng thái Thinking giúp tui');
assert.equal(fallbackTitle([]), null);
db.addMessage('title-msg',s.id,'user',history[1].content);
assert(db.updateAutoTitle(s.id,s.title,fallbackTitle(history)));
const named = db.getSession(s.id);
db.addMessage('title-answer',s.id,'agent','Okay');
assert(db.updateAutoTitle(s.id,named.title,'Thiết kế trạng thái Thinking'));
const signal = new AbortController().signal;
const mock = {streamChat: async opts => {assert.deepEqual(opts.tools,[]); opts.onChunk('“Thiết kế icon Thinking”');}};
assert.equal(await generateTitle({llm:mock,history,signal}), 'Thiết kế icon Thinking');
assert.equal(await generateTitle({llm:{streamChat:async()=>{throw Error('offline');}},history,signal}),null);
const original = db.getSession(s.id).title;
db.updateSession(s.id,original);
assert.equal(db.updateAutoTitle(s.id,original,'Không được ghi đè'),null);
assert.equal(db.getSession(s.id).title,original);
db.createSession('auto-run-session','title-agent','Phiên làm việc 20');
const events = [];
const loop = new AgentLoop({db, tools:{forStandalone(){return this;},getAllDefinitions:()=>[]}, permissions:{}, skills:{}, llm:{streamChat:async opts=>{opts.onChunk(opts.messages[0].content.startsWith('Name this conversation') ? 'Thiết kế icon trạng thái' : 'Mình sẽ giúp bạn.'); return {completed:true};}}});
loop.on('event',event=>events.push(event));
await loop.run({runId:'auto-title-run',sessionId:'auto-run-session',prompt:'Thiết kế icon trạng thái giúp tui'});
assert.equal(db.getSession('auto-run-session').title,'Thiết kế icon trạng thái');
assert(events.some(e=>e.type==='SessionTitleUpdated'));
assert(events.some(e=>e.type==='RunCompleted'));
assert.equal(db.getMessages('auto-run-session').length,2);
for (const greeting of ['chào bạn nha', 'aloo', 'bạn ơi', 'bạn là ai á', 'chào fen', 'fen khỏe k', 'alo ní nha']) assert(isGreeting(greeting));
assert(!isGreeting('chào bạn, sửa lỗi build giúp tui'));
db.createSession('greeting-session','title-agent','Đoạn chat mới');
await loop.run({runId:'greeting-run',sessionId:'greeting-session',prompt:'chào bạn nha'});
assert.equal(db.getSession('greeting-session').title,'Thiết kế icon trạng thái');
assert.equal(db.getSession('greeting-session').title_topic_set,1);
await loop.run({runId:'topic-run',sessionId:'greeting-session',prompt:'Thiết kế icon trạng thái giúp tui'});
assert.equal(db.getSession('greeting-session').title,'Thiết kế icon trạng thái');
assert.equal(db.getSession('greeting-session').title_topic_set,1);
await loop.run({runId:'later-topic-run',sessionId:'greeting-session',prompt:'Giờ sửa lỗi build nhé'});
assert.equal(db.getSession('greeting-session').title,'Thiết kế icon trạng thái');
db.createSession('manual-greeting','title-agent','Đoạn chat mới');
db.updateSession('manual-greeting','Trò chuyện của tui');
await loop.run({runId:'manual-title-run',sessionId:'manual-greeting',prompt:'Thiết kế icon trạng thái giúp tui'});
assert.equal(db.getSession('manual-greeting').title,'Trò chuyện của tui');
db.createSession('old-greeting','title-agent','Bắt đầu cuộc trò chuyện mới');
db.updateAutoTitle('old-greeting','Bắt đầu cuộc trò chuyện mới','Bắt đầu cuộc trò chuyện mới',true);
assert(db.resetGreetingTitle('old-greeting','Bắt đầu cuộc trò chuyện mới','Trò chuyện với trợ lý'));
assert.equal(db.getSession('old-greeting').title_topic_set,0);
db.updateSession('old-greeting','Tên riêng');
assert.equal(db.resetGreetingTitle('old-greeting','Tên riêng','Trò chuyện với trợ lý'),null);
console.log('✓ Automatic titles, fallback, message updates and manual title protection passed');
db.close();
