const {app,BrowserWindow,nativeImage}=require('electron');
const http=require('node:http'),assert=require('node:assert/strict');
app.setPath('userData',require('node:fs').mkdtempSync(require('node:path').join(require('node:os').tmpdir(),'ohmyt-computer-')));
const {IntegratedBrowser}=require('../electron/browser.cjs');
app.whenReady().then(async()=>{
 const server=http.createServer((_req,res)=>res.end(`<style>body{margin:0}button{position:absolute;left:40px;top:40px;width:100px;height:50px}input{position:absolute;left:40px;top:120px}canvas{position:absolute;left:40px;top:200px}</style><div id="sc" style="position:absolute;left:400px;top:20px;width:150px;height:120px;overflow:auto"><div style="height:1000px">Scroll</div></div><button onmousemove="window.hovered=true" ondblclick="window.doubles=(window.doubles||0)+1" onclick="this.textContent='Done'">Click</button><input><canvas width="300" height="160"></canvas><script>window.moves=0;const c=document.querySelector('canvas');c.onmousedown=()=>window.down=true;c.onmousemove=e=>{if(window.down&&e.buttons)window.moves++};window.onmouseup=()=>window.down=false;</script>`));
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=new IntegratedBrowser(),host=new BrowserWindow({width:1000,height:800,show:true});
 browser.attach(host,{x:200,y:0,width:600,height:700});
 const id=browser.add(`http://127.0.0.1:${server.address().port}`),wc=browser.tabs.get(id).webContents;
 await new Promise(r=>wc.once('did-finish-load',r));
 let owner='run-a';
 const observe=()=>browser.command('observe',{tabId:id,computerOwner:owner});
 const act=(s,a)=>browser.command('act',{tabId:id,computerOwner:owner,snapshotId:s.snapshotId,...a});
 let s=await observe();assert.match(s.image.dataUrl,/^data:image\/jpeg;base64,/);assert.equal(s.viewportWidth,600);assert.deepEqual(nativeImage.createFromDataURL(s.image.dataUrl).getSize(),{width:s.width,height:s.height});
 const xy=(s,x,y)=>({x:x*s.width/s.viewportWidth,y:y*s.height/s.viewportHeight});
 await assert.rejects(act(s,{action:'click',x:-1,y:20}),/Tọa độ/);
 await assert.rejects(browser.command('act',{tabId:id,computerOwner:'other',snapshotId:s.snapshotId,action:'click',x:60,y:60}),/Snapshot/);
 s=await act(s,{action:'move',...xy(s,80,60)});assert.equal(await wc.executeJavaScript("window.hovered"),true);
 s=await act(s,{action:'scroll',...xy(s,450,60),deltaY:-300});assert.ok(await wc.executeJavaScript("document.getElementById('sc').scrollTop")>0);
 const old=s;s=await act(s,{action:'click',...xy(s,80,60)});assert.equal(await wc.executeJavaScript("document.querySelector('button').textContent"),'Done');
 s=await act(s,{action:'click',...xy(s,80,60),clickCount:2});assert.equal(await wc.executeJavaScript('window.doubles'),1);
 await assert.rejects(act(old,{action:'click',x:60,y:60}),/Snapshot/);
 s=await act(s,{action:'click',...xy(s,80,130)});s=await act(s,{action:'type',text:'Tiếng Việt ✓'});assert.equal(await wc.executeJavaScript("document.querySelector('input').value"),'Tiếng Việt ✓');
 s=await act(s,{action:'keypress',key:'Tab'});
 s=await act(s,{action:'drag',...xy(s,60,230),endX:200*s.width/s.viewportWidth,endY:300*s.height/s.viewportHeight});assert.ok(await wc.executeJavaScript('window.moves')>0);
 s=await observe();await wc.executeJavaScript("document.querySelector('button').textContent='Changed'");await assert.rejects(act(s,{action:'click',...xy(s,80,60)}),/Snapshot/);
 await wc.executeJavaScript("document.querySelector('input').type='password'");s=await observe();await assert.rejects(act(s,{action:'click',...xy(s,80,130)}),/nhạy cảm/);await wc.executeJavaScript("document.querySelector('input').type='text'");
 wc.setZoomFactor(1.5);s=await observe();s=await act(s,{action:'click',...xy(s,120,90)});assert.equal(await wc.executeJavaScript("document.querySelector('button').textContent"),'Done');wc.setZoomFactor(1);
 s=await observe();host.setSize(1100,800);browser.attach(host,{x:200,y:0,width:650,height:700});await assert.rejects(act(s,{action:'click',x:60,y:60}),/Snapshot/);
 s=await observe();const pending=act(s,{action:'drag',...xy(s,60,230),endX:200*s.width/s.viewportWidth,endY:300*s.height/s.viewportHeight});setTimeout(()=>browser.computer.stop(id),50);await assert.rejects(pending,/dừng/);assert.equal(await wc.executeJavaScript('window.down'),false);
 await assert.rejects(observe(),/dừng/);owner='run-b';s=await observe();browser.computer.input(id,{type:'mouseDown',x:555,y:444});await assert.rejects(observe(),/dừng/);owner='run-c';
 browser.attach(host,null);await assert.rejects(observe(),/Mở khung/);
 host.close();server.close();console.log('PASS computer use: screenshot, coordinates, Unicode, drag, stale/owner/resize, cancellation');app.quit();
}).catch(e=>{console.error(e);app.exit(1);});
