const {app,BrowserWindow}=require('electron');const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const temp=fs.mkdtempSync(path.join(os.tmpdir(),'harness-controls-ui-'));app.setPath('userData',path.join(temp,'electron'));
app.whenReady().then(async()=>{const {createDaemon}=await import('../server/index.js');let release;const waiting=new Promise(r=>release=r);const daemon=createDaemon({dbPath:':memory:',port:0,dataDir:temp,pluginOverrides:{'core/llm':{name:'core/llm',apply(ctx){ctx.provide('llm',{streamChat:async({messages,onToolCall,onChunk})=>{const lastUser=[...messages].reverse().find(m=>m.role==='user');if(lastUser?.content==='Initial request'&&!messages.some(m=>m.role==='tool'))onToolCall({id:'slow',name:'fixture_slow',arguments:{}});else onChunk('Verified result for '+lastUser?.content);return {completed:true};}});}}},plugins:[{name:'fixture/slow',inject:['tools'],apply(ctx){ctx.effect(()=>ctx.tools.register({name:'fixture_slow',scopes:['standalone'],description:'Wait for fixture',parameters:{type:'object',properties:{},additionalProperties:false},execute:async()=>{await waiting;return 'observed';}}));}}]});daemon.db.createSession('controls',daemon.db.getAgents()[0].id,'Controls');daemon.db.setPolicy('fixture_slow:*','ALLOW');const {port}=await daemon.start();const w=new BrowserWindow({width:1280,height:800,show:true});
try{await fetch(`http://127.0.0.1:${port}/api/runs`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sessionId:'controls',prompt:'Initial request'})});await w.loadURL(`http://127.0.0.1:${port}/#session/controls`);await new Promise(r=>setTimeout(r,1600));const before=await w.webContents.executeJavaScript('document.body.innerText');assert.doesNotMatch(before,/Send after this reply|Gửi khi trả lời xong/);
await w.webContents.executeJavaScript(`(()=>{const field=document.querySelector('textarea');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(field,'Queued request');field.dispatchEvent(new Event('input',{bubbles:true}));})()`);await new Promise(r=>setTimeout(r,100));
assert.equal(await w.webContents.executeJavaScript("document.querySelector('.composer-busy-options')===null && !document.querySelector('button[aria-label=\"Gửi yêu cầu\"]').disabled"),true);
for(const width of [1280,720,480]){
  w.setSize(width,800);await new Promise(r=>setTimeout(r,150));
  const layout=await w.webContents.executeJavaScript(`(()=>{const shell=document.querySelector('.composer-shell'),toolbar=document.querySelector('.composer-toolbar');const bounds=shell.getBoundingClientRect();return {overflow:toolbar.scrollWidth>toolbar.clientWidth+1,outside:[...toolbar.querySelectorAll('button')].filter(el=>el.getClientRects().length).some(el=>{const r=el.getBoundingClientRect();return r.right>bounds.right+1||r.left<bounds.left-1;})};})()`);
  assert.equal(layout.overflow,false,`Toolbar overflow at ${width}px`);assert.equal(layout.outside,false,`Controls outside composer at ${width}px`);
}
await w.webContents.executeJavaScript(`document.querySelector('button[aria-label="Gửi yêu cầu"]').click()`);await new Promise(r=>setTimeout(r,300));assert.equal(daemon.harness.inbox.list('controls')[0].content,'Queued request');assert.equal(await w.webContents.executeJavaScript("document.querySelectorAll('.harness-pending-actions button').length"),3);
await w.webContents.executeJavaScript(`document.querySelector('button[aria-label="Gửi ngay"],button[aria-label="Send now"]').click()`);await new Promise(r=>setTimeout(r,300));
assert.equal(daemon.harness.inbox.list('controls')[0].kind,'steering');
await w.webContents.executeJavaScript(`document.querySelector('button[aria-label="Chờ tác vụ hoàn tất"],button[aria-label="Wait until task finishes"]').click()`);await new Promise(r=>setTimeout(r,300));
assert.equal(daemon.harness.inbox.list('controls')[0].kind,'queued');
const sendText=async text=>{await w.webContents.executeJavaScript(`(()=>{const field=document.querySelector('textarea');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(field,${JSON.stringify(text)});field.dispatchEvent(new Event('input',{bubbles:true}));})()`);await new Promise(r=>setTimeout(r,60));await w.webContents.executeJavaScript(`document.querySelector('button[aria-label="Gửi yêu cầu"]').click()`);await new Promise(r=>setTimeout(r,250));};
await sendText('Immediate instruction');
await w.webContents.executeJavaScript(`document.querySelectorAll('.harness-pending-row')[1].querySelector('button[aria-label="Gửi ngay"],button[aria-label="Send now"]').click()`);await new Promise(r=>setTimeout(r,250));
assert.equal(daemon.harness.inbox.list('controls')[1].kind,'steering');
await sendText('Delete this request');
await w.webContents.executeJavaScript(`document.querySelectorAll('.harness-pending-row')[2].querySelector('button[aria-label="Xóa tác vụ chờ"],button[aria-label="Delete pending task"]').click()`);await new Promise(r=>setTimeout(r,250));
assert(!daemon.harness.inbox.list('controls').some(m=>m.content==='Delete this request'));
w.setSize(1280,800);await new Promise(r=>setTimeout(r,200));fs.mkdirSync('output',{recursive:true});fs.writeFileSync('output/pending-tasks-preview.png',(await w.webContents.capturePage()).toPNG());
release();await new Promise(r=>setTimeout(r,1700));assert(daemon.db.getMessages('controls').some(m=>m.sender==='user'&&m.content==='Immediate instruction'));assert(!daemon.db.getMessages('controls').some(m=>m.content==='Delete this request'));assert(daemon.db.getMessages('controls').some(m=>m.sender==='user'&&m.content==='Queued request'));assert.equal(daemon.harness.inbox.list('controls').length,0);console.log('Actual busy composer, durable queue and automatic next turn passed');}finally{release();w.close();await daemon.stop();fs.rmSync(temp,{recursive:true,force:true});}app.quit();}).catch(e=>{console.error(e);app.exit(1);});
