const {app,BrowserWindow,clipboard,nativeImage}=require('electron');
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const files=[path.join(root,'image-paste-qa.html'),path.join(root,'src/image-paste-qa.tsx')];
fs.writeFileSync(files[0],'<html><body><div id="root"></div><script type="module" src="/src/image-paste-qa.tsx"></script></body></html>');
fs.writeFileSync(files[1],`import React from 'react';import {createRoot} from 'react-dom/client';import {Composer} from './components/Composer.tsx';import './index.css';createRoot(document.getElementById('root')!).render(<div style={{padding:40}}><Composer providers={[]} selectedModel={null} onSelectModel={()=>{}} onSend={(text,images)=>{document.body.dataset.sent=JSON.stringify({text,images});return document.body.dataset.fail!=='true';}}/></div>);`);
const cleanup=()=>files.forEach(file=>{if(fs.existsSync(file))fs.unlinkSync(file);});
app.whenReady().then(async()=>{
  const win=new BrowserWindow({width:900,height:650,show:true,webPreferences:{contextIsolation:true,nodeIntegration:false,sandbox:true}});
  const wc=win.webContents;
  const waitFor=async expression=>{for(let i=0;i<80;i++){if(await wc.executeJavaScript(expression))return;await new Promise(r=>setTimeout(r,50));}throw new Error('Timeout: '+expression);};
  await win.loadURL('http://127.0.0.1:5173/image-paste-qa.html');
  await waitFor('Boolean(document.querySelector("textarea"))');
  await wc.executeJavaScript('document.querySelector("textarea").focus()');
  const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
  clipboard.writeImage(nativeImage.createFromBuffer(Buffer.from(png,'base64')));
  wc.paste();
  await waitFor('Boolean(document.querySelector(".message-image img"))');
  assert.equal(await wc.executeJavaScript('document.querySelector("textarea").value'),'');
  assert.equal(await wc.executeJavaScript('document.querySelector("[aria-label=\"Gửi yêu cầu\"]").disabled'),false);
  await wc.executeJavaScript('document.querySelector(".message-image-open").click()');
  await waitFor('Boolean(document.querySelector("dialog[open]"))');
  await wc.executeJavaScript('document.querySelector("[aria-label=\"Đóng ảnh\"]").click()');
  await waitFor('!document.querySelector("dialog")');
  // Failed send must retain the pasted image for retry.
  await wc.executeJavaScript('document.body.dataset.fail="true";document.querySelector("[aria-label=\"Gửi yêu cầu\"]").click()');
  await waitFor('Boolean(document.body.dataset.sent)');
  assert.equal(await wc.executeJavaScript('document.querySelectorAll(".message-image").length'),1);
  await wc.executeJavaScript('document.body.dataset.fail="false";document.querySelector("[aria-label=\"Gửi yêu cầu\"]").click()');
  await waitFor('document.querySelectorAll(".message-image").length===0');
  const sent=JSON.parse(await wc.executeJavaScript('document.body.dataset.sent'));
  assert.equal(sent.text,'');assert.equal(sent.images.length,1);assert.ok(sent.images[0].dataUrl.startsWith('data:image/png;base64,'));
  await wc.executeJavaScript('document.querySelector("textarea").focus()');wc.paste();
  await waitFor('document.querySelectorAll(".message-image").length===1');
  await wc.executeJavaScript('document.querySelector("[aria-label=\"Bỏ ảnh 1\"]").click()');
  await waitFor('document.querySelectorAll(".message-image").length===0');
  clipboard.writeText('Văn bản đã dán');await wc.executeJavaScript('document.querySelector("textarea").focus()');wc.paste();
  await waitFor('document.querySelector("textarea").value==="Văn bản đã dán"');
  console.log('PASS image paste: clipboard, image-only send, failed send retry, enlarge, remove, plain text paste');
  win.close();cleanup();app.quit();
}).catch(error=>{console.error(error);cleanup();app.exit(1);});
