import {validateProfile,resolveProfile} from './manifests.js';
export class Profiles {
  constructor(database,host){this.db=database.db;this.host=host;this.db.exec('CREATE TABLE IF NOT EXISTS harness_profiles(id TEXT PRIMARY KEY,value TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1); CREATE TABLE IF NOT EXISTS harness_profile_selection(id INTEGER PRIMARY KEY CHECK(id=1),profile_id TEXT NOT NULL);CREATE TABLE IF NOT EXISTS harness_session_profiles(session_id TEXT PRIMARY KEY REFERENCES sessions(id) ON DELETE CASCADE,profile_id TEXT NOT NULL);CREATE TABLE IF NOT EXISTS harness_project_profiles(project_id TEXT PRIMARY KEY REFERENCES projects(id) ON DELETE CASCADE,profile_id TEXT NOT NULL);');}
  list(){const saved=this.db.prepare('SELECT * FROM harness_profiles ORDER BY id').all().map(row=>({...JSON.parse(row.value),revision:row.revision}));return [{id:'default',version:1,name:'Mặc định',budgets:this.host.config,revision:1,readonly:true},...saved];}
  save(profile,expectedRevision=0){
    this.host.assertIdle();validateProfile(profile);validateProfile({...profile,budgets:{...this.host.config,...profile.budgets}});for(const id of profile.plugins || [])if(!this.host.definitions.has(id))throw new Error(`Unknown extension: ${id}`);if(profile.scope)throw new Error('Presets cannot change execution scope');if(profile.id==='default')throw new Error('Default preset is managed by runtime');
    const row=this.db.prepare('SELECT revision FROM harness_profiles WHERE id=?').get(profile.id);if((row?.revision || 0)!==expectedRevision)throw Object.assign(new Error('Preset changed; reload before saving'),{statusCode:409});
    return this._atomic(()=>{const revision=expectedRevision+1;this.db.prepare('INSERT INTO harness_profiles VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value,revision=excluded.revision').run(profile.id,JSON.stringify(profile),revision);return {...profile,revision};});
  }
  selectedId(sessionId=null){const session=sessionId?this.host.agentLoop.db.getSession(sessionId):null;return (sessionId?this.db.prepare('SELECT profile_id FROM harness_session_profiles WHERE session_id=?').get(sessionId)?.profile_id:null) || (session?.project_id?this.db.prepare('SELECT profile_id FROM harness_project_profiles WHERE project_id=?').get(session.project_id)?.profile_id:null) || this.db.prepare('SELECT profile_id FROM harness_profile_selection WHERE id=1').get()?.profile_id || 'default';}
  selected(sessionId=null){const globalId=this.db.prepare('SELECT profile_id FROM harness_profile_selection WHERE id=1').get()?.profile_id || 'default',session=sessionId?this.host.agentLoop.db.getSession(sessionId):null;const projectId=session?.project_id?this.db.prepare('SELECT profile_id FROM harness_project_profiles WHERE project_id=?').get(session.project_id)?.profile_id:null,explicitId=sessionId?this.db.prepare('SELECT profile_id FROM harness_session_profiles WHERE session_id=?').get(sessionId)?.profile_id:null;const clean=id=>{if(!id)return {};const {revision,readonly,...profile}=this.get(id) || this.get('default');return profile;};return resolveProfile(clean(globalId),clean(projectId),clean(explicitId));}
  select(id,{sessionId=null,projectId=null}={}){this.host.assertIdle();if(!this.get(id))throw new Error('Preset unavailable');return this._atomic(()=>{if(sessionId){if(!this.host.agentLoop.db.getSession(sessionId))throw new Error('Chat unavailable');this.db.prepare('INSERT INTO harness_session_profiles VALUES(?,?) ON CONFLICT(session_id) DO UPDATE SET profile_id=excluded.profile_id').run(sessionId,id);}else if(projectId){if(!this.host.agentLoop.db.getProject(projectId))throw new Error('Project unavailable');this.db.prepare('INSERT INTO harness_project_profiles VALUES(?,?) ON CONFLICT(project_id) DO UPDATE SET profile_id=excluded.profile_id').run(projectId,id);}else this.db.prepare('INSERT INTO harness_profile_selection VALUES(1,?) ON CONFLICT(id) DO UPDATE SET profile_id=excluded.profile_id').run(id);return this.selected(sessionId);});}
  _atomic(update){this.db.exec('SAVEPOINT profile_update');try{const result=update();this._validateLayers();this.db.exec('RELEASE profile_update');return result;}catch(error){this.db.exec('ROLLBACK TO profile_update; RELEASE profile_update');throw error;}}
  _validateLayers(){const base=this.selected();for(const row of this.db.prepare('SELECT profile_id FROM harness_project_profiles').all()){const {revision,readonly,...profile}=this.get(row.profile_id);resolveProfile(base,profile);}for(const row of this.db.prepare('SELECT id FROM sessions').all())this.selected(row.id);}
  get(id){return this.list().find(p=>p.id===id);}
}
