import {useEffect,useState} from 'react';
import {api,type AgentPreset} from '../api.ts';
export function AgentPresets({en}:{en:boolean}){
 const [presets,setPresets]=useState<AgentPreset[]>([]),[selected,setSelected]=useState('default'),[editing,setEditing]=useState<AgentPreset|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const value=await api.getPresets();setPresets(value.presets);setSelected(value.selectedId);};
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await load();setEditing(null);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 return <section className="harness-settings"><h2>{en?'Agent presets':'Cấu hình agent'}</h2><p className="harness-help">{en?'Choose a configuration for new runs. Changes require all runs to finish.':'Chọn cấu hình cho các lượt chạy mới. Chỉ đổi được khi các tác vụ đã dừng.'}</p>{error&&<p role="alert">{error}</p>}<label className="harness-field"><span>{en?'Active preset':'Cấu hình đang dùng'}</span><select disabled={busy} value={selected} onChange={e=>void action(()=>api.selectPreset(e.target.value))}>{presets.map(p=><option key={p.id} value={p.id}>{p.id==='default'?(en?'Application default':'Mặc định của ứng dụng'):p.name || p.id}</option>)}</select></label><div className="harness-actions"><button disabled={busy} onClick={()=>setEditing({id:`preset-${Date.now()}`,version:1,name:'',revision:0,budgets:{maxSteps:5,browserMaxSteps:20,contextTokens:24000,reserveTokens:4000,toolResultTokens:4000}})}>{en?'New preset':'Tạo cấu hình'}</button>{presets.find(p=>p.id===selected&&!p.readonly)&&<button disabled={busy} onClick={()=>setEditing(presets.find(p=>p.id===selected)!)}>{en?'Edit preset':'Sửa cấu hình'}</button>}</div>{editing&&<form onSubmit={e=>{e.preventDefault();const {revision,readonly,...profile}=editing;void action(()=>api.savePreset(profile,revision));}}><label className="harness-field"><span>{en?'Name':'Tên'}</span><input required autoFocus maxLength={100} value={editing.name || ''} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><details><summary>{en?'Execution limits':'Giới hạn thực thi'}</summary>{Object.entries(editing.budgets || {}).map(([key,value])=><label className="harness-field" key={key}><span>{{maxSteps:en?'Tool rounds':'Lượt gọi tool',browserMaxSteps:en?'Browser rounds':'Lượt trình duyệt',contextTokens:en?'Context tokens':'Token ngữ cảnh',reserveTokens:en?'Reserved tokens':'Token dự phòng',toolResultTokens:en?'Tool result tokens':'Token kết quả tool'}[key] || key}</span><input type="number" required min={1} value={value} onChange={e=>setEditing({...editing,budgets:{...editing.budgets,[key]:Number(e.target.value)}})}/></label>)}</details><div className="harness-actions"><button disabled={busy} type="submit">{en?'Save preset':'Lưu cấu hình'}</button><button disabled={busy} type="button" onClick={()=>setEditing(null)}>{en?'Cancel':'Huỷ'}</button></div></form>}</section>;
}
