import React,{useEffect,useRef,useState} from 'react';
import {X,Download,Copy} from 'lucide-react';
import {api,type ArtifactItem} from '../api.ts';
import {copyToClipboard} from '../clipboard.ts';
import {clientRegistry} from '../harness/clientRegistry.ts';
export function ArtifactPane({artifactId,sessionId,onClose}:{artifactId:string;sessionId:string;onClose:()=>void}){
  const [artifact,setArtifact]=useState<ArtifactItem|null>(null),[error,setError]=useState(''),[copied,setCopied]=useState(false),[loading,setLoading]=useState(true);const close=useRef<HTMLButtonElement>(null);const en=document.documentElement.lang==='en';
  useEffect(()=>{let disposed=false;setLoading(true);setError('');void api.getArtifact(artifactId,sessionId).then(value=>{if(!disposed)setArtifact(value);}).catch(e=>{if(!disposed)setError(e.message);}).finally(()=>{if(!disposed)setLoading(false);});close.current?.focus();return()=>{disposed=true;};},[artifactId,sessionId]);
  const download=()=>{if(!artifact)return;const url=URL.createObjectURL(new Blob([artifact.content],{type:artifact.mime}));const anchor=document.createElement('a');anchor.href=url;anchor.download=artifact.title;anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const renderer=artifact&&clientRegistry.list('artifact.renderer').find(r=>r.matches?.(artifact));
  return <section className="harness-artifact-pane" aria-label={en?'Artifact preview':'Xem tài liệu'} onKeyDown={e=>{if(e.key==='Escape')onClose();}}><header><h2>{artifact?.title || (en?'Document':'Tài liệu')}</h2><button ref={close} aria-label={en?'Close preview':'Đóng tài liệu'} onClick={onClose}><X size={16}/></button></header>{loading?<p role="status">{en?'Loading…':'Đang tải…'}</p>:error?<p role="alert">{error}</p>:artifact&&<><div className="harness-artifact-actions"><button onClick={download}><Download size={14}/>{en?'Download':'Tải xuống'}</button><button onClick={()=>void copyToClipboard(artifact.content).then(()=>setCopied(true)).catch(()=>setError(en?'Could not copy':'Không sao chép được'))}><Copy size={14}/>{copied?(en?'Copied':'Đã sao chép'):(en?'Copy':'Sao chép')}</button></div>{renderer?<RendererBoundary fallback={artifact.content}>{renderer.render(artifact)}</RendererBoundary>:artifact.mime==='text/html'||artifact.mime==='image/svg+xml'?<iframe title={artifact.title} sandbox="" referrerPolicy="no-referrer" srcDoc={`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:;">${artifact.content}`}/>:<pre>{artifact.content}</pre>}</>}</section>;
}
class RendererBoundary extends React.Component<{children:React.ReactNode;fallback:string},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?<pre>{this.props.fallback}</pre>:this.props.children;}}
