import {useEffect,useState} from 'react';
import {api,type ConnectorItem} from '../api.ts';
import type {SettingsLocale} from '../appearance.ts';
export function ConnectorSettings({locale}:{locale:SettingsLocale}){
 const en=locale==='en',[items,setItems]=useState<ConnectorItem[]>([]),[projects,setProjects]=useState<{id:string;name:string}[]>([]),[editing,setEditing]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[notice,setNotice]=useState('');
 const [expectedRevision,setExpectedRevision]=useState(0);
 const [form,setForm]=useState({id:'',name:'',transport:'http' as 'http'|'stdio',url:'',command:'',args:'',scopeId:'standalone',token:''});
 const load=async()=>{setLoading(true);try{setItems((await api.getConnectors()).connectors);setProjects(await api.getProjects());}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const action=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');setNotice('');try{await fn();await load();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 const labels=en?{add:'Add connection',name:'Name',id:'Connection ID',url:'MCP endpoint',command:'Executable',args:'Arguments (one per line)',scope:'Available in',token:'Bearer token',save:'Save',cancel:'Cancel',test:'Test',connect:'Connect',disconnect:'Disconnect'}:{add:'Thêm kết nối',name:'Tên',id:'ID kết nối',url:'Địa chỉ MCP',command:'Lệnh chạy',args:'Tham số (mỗi dòng một giá trị)',scope:'Phạm vi sử dụng',token:'Bearer token',save:'Lưu',cancel:'Hủy',test:'Kiểm tra',connect:'Kết nối',disconnect:'Ngắt kết nối'};
 return <div className="harness-settings" onKeyDown={e=>{if(e.key==='Escape'&&editing&&!busy){e.stopPropagation();setEditing(false);}}}>{error&&<p className="harness-inline-error" role="alert">{error}<button onClick={()=>void load()} disabled={busy}>{en?'Reload':'Tải lại'}</button></p>}{notice&&<p className="harness-help" role="status">{notice}</p>}
 {editing?<form onSubmit={e=>{e.preventDefault();void action(async()=>{await api.saveConnector({...form,expectedRevision,args:form.args.split('\n').filter(Boolean),token:form.token || undefined});setEditing(false);});}}>
 <h2>{expectedRevision?(en?'Edit connection':'Sửa kết nối'):labels.add}</h2>{(['id','name'] as const).map(key=><label className="harness-field" key={key}><span>{labels[key]}</span><input autoFocus={key===(expectedRevision?'name':'id')} readOnly={key==='id'&&expectedRevision>0} required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}
 <label className="harness-field"><span>{en?'Transport':'Giao thức'}</span><select value={form.transport} onChange={e=>setForm({...form,transport:e.target.value as 'http'|'stdio'})}><option value="http">Streamable HTTP</option><option value="stdio">stdio</option></select></label>
 {form.transport==='http'?<><label className="harness-field"><span>{labels.url}</span><input required type="url" value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></label><label className="harness-field"><span>{labels.token}</span><input placeholder={expectedRevision?(en?'Leave blank to keep saved credential':'Để trống để giữ thông tin đã lưu'):undefined} autoComplete="off" type="password" value={form.token} onChange={e=>setForm({...form,token:e.target.value})}/></label></>:<><p className="harness-help">{en?'This executable runs on your computer. Add only servers you trust.':'Lệnh này chạy trên máy. Chỉ thêm server bạn tin cậy.'}</p><label className="harness-field"><span>{labels.command}</span><input required value={form.command} onChange={e=>setForm({...form,command:e.target.value})}/></label><label className="harness-field"><span>{labels.args}</span><textarea value={form.args} onChange={e=>setForm({...form,args:e.target.value})}/></label></>}
 <label className="harness-field"><span>{labels.scope}</span><select value={form.scopeId} onChange={e=>setForm({...form,scopeId:e.target.value})}><option value="standalone">{en?'Chats outside projects':'Chat ngoài project'}</option>{projects.map(p=><option key={p.id} value={`project:${p.id}`}>{p.name}</option>)}</select></label>
 <div className="harness-actions"><button disabled={busy}>{busy?(en?'Saving…':'Đang lưu…'):labels.save}</button><button type="button" disabled={busy} onClick={()=>setEditing(false)}>{labels.cancel}</button></div></form>:<><div className="harness-list-heading"><p className="harness-help">{en?'Connect external tools with a defined scope. Calls still follow approval policy.':'Kết nối công cụ theo phạm vi. Mọi lời gọi vẫn tuân theo chế độ duyệt.'}</p><button onClick={()=>{setExpectedRevision(0);setForm({id:'',name:'',transport:'http',url:'',command:'',args:'',scopeId:'standalone',token:''});setEditing(true);setError('');}}>{labels.add}</button></div>
 {loading&&!items.length?<p role="status">{en?'Loading…':'Đang tải…'}</p>:!items.length?<p className="harness-help">{en?'No connections yet.':'Chưa có kết nối.'}</p>:items.map(item=><div className="harness-connector-row" key={item.id}><div><strong>{item.name || item.id}</strong><small>{item.transport} · {item.scopeId==='standalone'?(en?'Outside projects':'Ngoài project'):projects.find(p=>`project:${p.id}`===item.scopeId)?.name || item.scopeId}</small><span>{item.state==='error'?(en?'Connection lost — reconnect':'Mất kết nối — kết nối lại'):item.state==='connected'?(en?'Connected':'Đã kết nối'):(en?'Disconnected':'Chưa kết nối')}</span></div><div className="harness-actions">{item.state==='disconnected'&&<button disabled={busy} onClick={()=>{setExpectedRevision(item.revision);setForm({id:item.id,name:item.name || item.id,transport:item.transport,url:item.url || '',command:item.command || '',args:(item.args || []).join('\n'),scopeId:item.scopeId,token:''});setEditing(true);setError('');}}>{en?'Edit':'Sửa'}</button>}<button disabled={busy} onClick={()=>void action(async()=>{const result=await api.connectorAction(item.id,'test');setNotice(result.connected?(en?'Connection test passed.':'Kiểm tra kết nối thành công.'):String(result.error || (en?'Connection failed.':'Kết nối thất bại.')));})}>{labels.test}</button><button disabled={busy} onClick={()=>void action(()=>api.connectorAction(item.id,item.state==='connected'||item.state==='error'?'disconnect':'connect'))}>{item.state==='connected'||item.state==='error'?labels.disconnect:labels.connect}</button></div></div>)}</>}
 </div>;
}
