import {AgentPresets} from './AgentPresets.tsx';
import React,{useEffect,useRef,useState} from 'react';
import {ArrowLeft,ChevronRight,RefreshCw} from 'lucide-react';
import {api,type ExtensionItem} from '../api.ts';
import type {SettingsLocale} from '../appearance.ts';
export function ExtensionSettings({locale}:{locale:SettingsLocale}){
  const en=locale==='en';const [items,setItems]=useState<ExtensionItem[]>([]),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[config,setConfig]=useState<Record<string,unknown>>({});
  const back=useRef<HTMLButtonElement>(null),list=useRef<HTMLDivElement>(null);
  const load=async()=>{setLoading(true);setError('');try{setItems((await api.getExtensions()).extensions);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);
  const item=items.find(i=>i.id===selected);
  useEffect(()=>{if(item){setConfig(item.config);back.current?.focus();}},[selected]);
  const close=()=>{const id=selected;setSelected(null);requestAnimationFrame(()=>list.current?.querySelector<HTMLButtonElement>(`[data-extension-id="${CSS.escape(id || '')}"] button`)?.focus());};
  const save=async(enabled:boolean)=>{if(!item)return;setSaving(true);setError('');try{const saved=await api.updateExtension(item.id,{enabled,config,expectedVersion:item.revision});setItems(prev=>prev.map(row=>row.id===saved.id?saved:row));}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setSaving(false);}};
  const label=(row:ExtensionItem)=>en?({'tools/workspace':'Files and runtime','tools/browser':'Browser','tools/memory':'Memory','tools/web':'Web search','skills/catalog':'Skills','tools/ptc':'Program execution','agents/subagents':'Child agents','artifacts/store':'Generated documents'}[row.id] || row.name):row.name;
  return <div className="harness-settings" onKeyDown={e=>{if(e.key==='Escape'&&selected&&!saving){e.stopPropagation();close();}}}>
    {error&&<div className="harness-inline-error" role="alert"><span>{error}</span><button onClick={()=>void load()} disabled={loading||saving}>{en?'Reload':'Tải lại'}</button></div>}
    {loading&&!items.length?<p role="status">{en?'Loading extensions…':'Đang tải tiện ích…'}</p>:item?<>
      <button ref={back} className="harness-back" onClick={close} disabled={saving}><ArrowLeft size={15}/>{en?'All extensions':'Tất cả tiện ích'}</button>
      <div className="harness-detail-heading"><h2>{label(item)}</h2><span>{item.enabled?(en?'Enabled':'Đang bật'):(en?'Disabled':'Đã tắt')}</span></div>
      {item.availability?.available===false&&<p role="status" className="harness-help">{en?'Program execution requires Linux sandbox support and a native Node runtime.':'Thực thi chương trình cần sandbox Linux và Node runtime riêng.'}</p>}{item.description&&<p className="harness-help">{item.description}</p>}
      <dl className="harness-facts"><dt>{en?'Source':'Nguồn'}</dt><dd>{item.source==='local'?(en?'Local application':'Ứng dụng trên máy'):item.source}</dd><dt>{en?'Dependencies':'Phụ thuộc'}</dt><dd>{item.dependencies.join(', ') || (en?'None':'Không có')}</dd><dt>{en?'Capabilities':'Khả năng'}</dt><dd>{item.capabilities.join(', ') || (en?'Managed by application':'Do ứng dụng quản lý')}</dd></dl>
      {Object.entries(item.configSchema?.properties || {}).filter(([,field])=>['string','number','integer','boolean'].includes(field.type || '')).map(([key,field])=><label className="harness-field" key={key}><span>{field.title || key}</span>{field.enum?<select value={String(config[key] ?? '')} onChange={e=>setConfig({...config,[key]:field.enum?.find(value=>String(value)===e.target.value)})}>{field.enum.map(value=><option key={String(value)}>{String(value)}</option>)}</select>:field.type==='boolean'?<input type="checkbox" checked={Boolean(config[key])} onChange={e=>setConfig({...config,[key]:e.target.checked})}/>:<input type={field.type==='string'?'text':'number'} value={String(config[key] ?? '')} onChange={e=>setConfig({...config,[key]:field.type==='string'?e.target.value:Number(e.target.value)})}/>}</label>)}
      {item.readonly?<p className="harness-help">{en?'This service is required by the application.':'Dịch vụ này là thành phần bắt buộc của ứng dụng.'}</p>:<div className="harness-actions"><button disabled={saving} onClick={()=>void save(!item.enabled)}>{saving?(en?'Saving…':'Đang lưu…'):item.enabled?(en?'Disable extension':'Tắt tiện ích'):(en?'Enable extension':'Bật tiện ích')}</button>{item.configSchema&&<button disabled={saving||!item.enabled} onClick={()=>void save(true)}>{en?'Save settings':'Lưu cấu hình'}</button>}</div>}
    </>:<><div className="harness-list-heading"><p className="harness-help">{en?'Manage capabilities installed in this application.':'Quản lý các khả năng đã có trong ứng dụng.'}</p><button aria-label={en?'Refresh extensions':'Tải lại tiện ích'} disabled={loading} onClick={()=>void load()}><RefreshCw size={15}/></button></div><div ref={list}>{items.filter(row=>!row.readonly).map(row=><div className="harness-extension-row" data-extension-id={row.id} key={row.id}><button onClick={()=>setSelected(row.id)}><span><strong>{label(row)}</strong><small>{row.readonly?(en?'Required service':'Dịch vụ bắt buộc'):row.builtin?(en?'Built in':'Có sẵn'):row.id}</small></span><span className="harness-row-state">{row.state==='unavailable'?(en?'Unavailable':'Chưa khả dụng'):row.state==='failed'?(en?'Error':'Lỗi'):row.enabled?(en?'Enabled':'Đang bật'):(en?'Disabled':'Đã tắt')}<ChevronRight size={15}/></span></button></div>)}</div><AgentPresets en={en}/><details className="harness-system-services"><summary>{en?'Required application services':'Dịch vụ hệ thống bắt buộc'}</summary>{items.filter(row=>row.readonly).map(row=><p key={row.id}>{row.name}</p>)}</details>{!items.length&&!error&&<p>{en?'No extensions installed.':'Chưa có tiện ích.'}</p>}</>}
  </div>;
}
